---
#Firewall play, only runs when update_firewall: set to true in wptb_vars.yml
# Install stuff
  # Centos
- name: "wptb_firewall.yml: CentOS Install iptables-services"
  yum:
    name: ['iptables-services']
    state: present
  when: ansible_distribution == 'CentOS'
  # Fedora
- name: "wptb_firewall.yml: Fedora Install iptables-services"
  dnf:
    name: ['iptables-services']
    state: present
  when: ansible_distribution == 'Fedora'

# Firewall stuff
- name: "wptb_firewall.yml: Stop & disable firewalld"
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: "wptb_firewall.yml: Start and and enable iptables"
  service:
    name: iptables
    state: started
    enabled: yes

- name: "wptb_firewall.yml: Flush existing firewall rules"
  iptables:
    flush: true
  notify: wptb_restart_iptables

- name: "wptb_firewall.yml: Allow related and established connections"
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: ansible related and established
  notify: wptb_restart_iptables

#Inbound rules
- name: "wptb_firewall.yml: Inbound web rules"
  iptables:
    chain: INPUT
    ctstate: NEW
    source: '{{ item.src }}'
    destination_port: '{{ item.dp }}'
    protocol: tcp
    jump: ACCEPT
    comment: ansible FW public Inbound Allow
  with_items:
    - { src: '0.0.0.0/0', dp: '80' }
    - { src: '0.0.0.0/0', dp: '443' }
  notify: wptb_restart_iptables

- name: "wptb_firewall.yml: Inbound ssh rules"
  iptables:
    chain: INPUT
    ctstate: NEW
    source: '{{ item[0] }}'
    destination_port: '{{ item[1] }}'
    protocol: tcp
    jump: ACCEPT
    comment: ansible FW local lan Inbound Allow
  with_nested:
    - '{{ wptb_loclan }}'
    - ['22']
  notify: wptb_restart_iptables
## Save the changes
- name: "wptb_firewall.yml: Save iptables"
  command: service iptables save
  args:
    warn: false
  notify: wptb_restart_iptables


